# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 18, 12, 53, 572723)),
        ),
        migrations.AddField(
            model_name='bookings',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 30, 18, 12, 53, 572832)),
        ),
    ]
