# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180723_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 13, 20, 2, 710971)),
        ),
    ]
