# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180724_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 26, 9, 58, 12, 802896)),
        ),
    ]
